<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module [
	<!ELEMENT module (module|property|metadata|message)*>
	<!ATTLIST module name NMTOKEN #REQUIRED>
	
	<!ELEMENT property EMPTY>
	<!ATTLIST property
	    name NMTOKEN #REQUIRED
	    value CDATA #REQUIRED
	    default CDATA #IMPLIED
	>
	<!ELEMENT metadata EMPTY>
	<!ATTLIST metadata
	    name NMTOKEN #REQUIRED
	    value CDATA #REQUIRED
	>
	<!ELEMENT message EMPTY>
	<!ATTLIST message
	    key NMTOKEN #REQUIRED
	    value CDATA #REQUIRED
	>
]>
<!-- 
	Checkstyle-Configuration: MPO Strict 
	Description: Strict checkstyle
-->
<module name="Checker">
	<property name="severity" value="warning" />
	<module name="TreeWalker">
		<property name="tabWidth" value="4" />
		<module name="AnnotationUseStyle" />
		<module name="MissingDeprecated" />
		<module name="MissingOverride">
			<property name="javaFiveCompatibility" value="true" />
		</module>
		<module name="PackageAnnotation" />
		<module name="SuppressWarnings" />
		<module name="PackageName">
			<property name="severity" value="error" />
		</module>
		<module name="ConstantName">
			<property name="severity" value="error" />
		</module>
		<module name="MethodName">
			<property name="severity" value="error" />
		</module>
		<module name="TypeName">
			<property name="severity" value="error" />
		</module>
		<module name="ClassTypeParameterName">
			<property name="severity" value="error" />
		</module>
		<module name="MethodTypeParameterName">
			<property name="severity" value="error" />
		</module>
		<module name="ParameterName">
			<property name="severity" value="error" />
			<property name="format" value="^a[a-zA-Z0-9]*$" />
		</module>
		<module name="StaticVariableName">
			<property name="severity" value="error" />
		</module>
		<module name="LocalFinalVariableName">
			<property name="severity" value="error" />
		</module>
		<module name="LocalVariableName">
			<property name="severity" value="error" />
		</module>
		<module name="MemberName">
			<property name="severity" value="error" />
		</module>
		<module name="AvoidStarImport">
			<property name="severity" value="error" />
		</module>
		<module name="AvoidStaticImport">
			<property name="severity" value="error" />
		</module>
		<module name="IllegalImport">
			<property name="severity" value="error" />
			<property name="illegalPkgs" value="sun,edu.emory.mathcs.backport" />
		</module>
		<module name="RedundantImport">
			<property name="severity" value="error" />
		</module>
		<module name="UnusedImports">
			<property name="severity" value="error" />
		</module>
		<module name="AnonInnerLength">
			<property name="max" value="50" />
		</module>
		<module name="LineLength">
			<property name="max" value="160" />
		</module>
		<module name="MethodLength" />
		<module name="ParameterNumber" />
		<module name="OuterTypeNumber" />
		<module name="GenericWhitespace" />
		<module name="ModifierOrder">
			<property name="severity" value="ignore" />
			<metadata name="net.sf.eclipsecs.core.lastEnabledSeverity" value="inherit" />
		</module>
		<module name="RedundantModifier">
			<property name="severity" value="error" />
		</module>
		<module name="AvoidNestedBlocks">
			<property name="severity" value="error" />
			<property name="allowInSwitchCase" value="true" />
		</module>
		<module name="EmptyBlock">
			<property name="severity" value="error" />
			<property name="option" value="text" />
		</module>
		<module name="ArrayTypeStyle">
			<property name="severity" value="error" />
		</module>
		<module name="TrailingComment" />
		<module name="UpperEll" />
		<module name="NeedBraces">
			<property name="tokens" value="LITERAL_DO,LITERAL_ELSE,LITERAL_IF,LITERAL_FOR,LITERAL_WHILE" />
		</module>
		<module name="NoWhitespaceAfter">
			<property name="tokens" value="ARRAY_INIT,BNOT,DEC,DOT,INC,LNOT" />
		</module>
		<module name="NoWhitespaceBefore" />
		<module name="MethodParamPad">
			<property name="allowLineBreaks" value="true" />
		</module>
		<module name="ParenPad" />
		<module name="TypecastParenPad" />
		<module name="WhitespaceAfter" />
		<module name="WhitespaceAround">
			<property name="allowEmptyConstructors" value="true" />
			<property name="allowEmptyMethods" value="true" />
		</module>
		<module name="WhitespaceAfter" />
		<module name="CovariantEquals" />
		<module name="DefaultComesLast">
			<property name="severity" value="error" />
		</module>
		<module name="EmptyStatement">
			<property name="severity" value="error" />
		</module>
		<module name="EqualsHashCode" />
		<module name="ExplicitInitialization" />
		<module name="FallThrough" />
		<module name="HiddenField">
			<property name="tokens" value="PARAMETER_DEF,VARIABLE_DEF,LAMBDA" />
		</module>
		<module name="InnerAssignment">
			<property name="severity" value="error" />
		</module>
		<module name="MissingSwitchDefault" />
		<module name="PackageDeclaration">
			<property name="severity" value="error" />
		</module>
		<module name="SimplifyBooleanExpression" />
		<module name="StringLiteralEquality">
			<property name="severity" value="error" />
		</module>
		<module name="UnnecessaryParentheses" />
		<module name="ArrayTrailingComma" />
		<module name="FinalClass" />
		<module name="HideUtilityClassConstructor" />
		<module name="InterfaceIsType" />
		<module name="JavadocStyle" />
		<module name="MultipleVariableDeclarations">
			<property name="severity" value="error" />
		</module>
		<module name="OneStatementPerLine">
			<property name="severity" value="error" />
		</module>
		<module name="InnerTypeLast">
			<property name="severity" value="ignore" />
			<metadata name="net.sf.eclipsecs.core.lastEnabledSeverity" value="inherit" />
		</module>
		<module name="VisibilityModifier">
			<property name="packageAllowed" value="true" />
			<property name="protectedAllowed" value="true" />
		</module>
		<module name="OuterTypeFilename">
			<property name="severity" value="error" />
		</module>
		<module name="DeclarationOrder" />
		<module name="AnnotationLocation" />
		<module name="JavadocMethod">
			<property name="minLineCount" value="1" />
			<property name="allowMissingJavadoc" value="true" />
			<property name="suppressLoadErrors" value="true" />
		</module>
		<module name="InterfaceTypeParameterName">
			<property name="severity" value="error" />
		</module>
		<module name="EmptyCatchBlock">
			<property name="severity" value="error" />
		</module>
	</module>
	<module name="FileLength" />
</module>
